### ISSUE TITLE
Does not affect Date.prototype.toLocaleString

### ISSUE THREAD

**Issue by jamesarosen** [boblauer/MockDate#19]
```js
// I'm in America/Los_Angeles (+08:00) during non-saving time:
(new Date()).getTimezoneOffset()
// 480

// 4pm in America/Chicago (+06:00) is 2pm in my local time:
(new Date('2001-02-03T04:05+06:00')).toLocaleString([], {hour: "2-digit",minute: "2-digit"})
// '2:05 PM'

// If I change to America/Denver (+07:00):
const MD = require('mockdate')
MD.set('2002-03-04T05:06+07:00', -420)

// then getTimezoneOffset is mocked:
(new Date()).getTimezoneOffset()
// 420

// but toLocaleString isn't:
(new Date('2001-02-03T04:05+06:00')).toLocaleString([], {hour: "2-digit",minute: "2-digit"})
// '2:05 PM'
```

**Comment by boblauer** [comment]
Taking in an offset as a 2nd parameter to `MockDate.set` was a mistake that I regret because it leads to confusing expectations on how it should work. The only thing it does is mock the result of `getTimezoneOffset`, but it has no effect on other methods that read that value.

Trying to modify every method whose return value is dependent upon the timezone offset would be too difficult, and is really not the purpose of this library.

I might release a new major version without the timezone offset parameter, because it's confusing and not very helpful.

Sorry, I know that's not the answer you wanted to hear.

**Comment by aaronbeall** [comment]
@boblauer Am I right that another part to this is that `new Date()` does not actually use the timezone used in `MockDate.set`? In other words `new Date(2019, 3, 2)` will create a date in the running system timezone?

**Comment by boblauer** [comment]
Yup, that is correct.
