### ISSUE TITLE
Mock getTimezoneOffset

### ISSUE THREAD

**Issue by klippx** [boblauer/MockDate#65]
Hello,

I found myself in need of mocking `getTimezoneOffset` to avoid flaky tests that should give deterministic results on CI and locally regardless of timezone of the environment running the suite. 

Right now this is "unmockable", running the suite in different time zones will get different results for `getTimezoneOffset` and this library provides no remedy even though I think it could/should.

So for the company I work at we had to do this manually. But the question arose during code review if this is someting that would be interesting to contribute to the MockDate repo?

In the simplest form, there could be a new separate API such as:

```
> MockDate.setTimeZoneOffset("+08:00")
> const date = new Date()
> date.getTimeZoneOffset()
< -480
```

This is rougher idea, but could also be mentioned: If you were to provide a `+HH:MM` syntax one could override `getTimeZoneOffset` based on that syntax:

```
> MockDate.set("2020-04-13T00:00:00.000+08:00")
> const date = new Date()
> date.getTimeZoneOffset()
< -480
```

But I feel that could be unintuitive and presumptious.

Thoughts? 🤔

**Comment by boblauer** [comment]
Mocking the timezone was possible with older version of MockDate, but I got rid of it because it was causing a lot of confusion and didn't work great.

For example, `.toString` still used the real timezone, not the mocked timezone. I would either want a full mock timezone implementation, where everything works with a mocked timezone exactly as it would if the system clock was in that timezone, or no implementation at all. Given how ridiculously complex a proper implementation is, I opted to remove it altogether.
