### ISSUE TITLE
setHours doesn't respect timezone offset

### ISSUE THREAD

**Issue by bojidar-bg** [boblauer/MockDate#9]
For example, doing: 
```
MockDate.set(0, 0);
a = new Date();
a.setHours(16);
console.log(a.toISOString());
```
would not produce `1970-01-01T16:00:00.000Z` but `1970-01-01T14:00:00.000Z` (when running in GMT+2)

**Comment by boblauer** [comment]
Sorry it took me so long to get to this.  It's a little misleading, but the timezone offset will not make the Date object behave as if it is in that timezone.  It was actually added as a way to fix a CI issue with tests running in a different timezone - https://github.com/boblauer/MockDate/pull/7

That may have been a mistake though, because the API does appear to allow you to specify which timezone you want your MockDates to exist in.

I'll have to think about what it would take to get all dates to respect the timezone offset.  The tricky part is not in `setHours`, but the other ways that the hour can be set, such as passing a number > 60 to `setMinutes`.  I'll need to ensure I'm consistent everywhere, which I think might be tricky.

**Comment by HunorMarton** [comment]
I think I experienced the same issue with different setup. Basically the timezone parameter has no effect on the date, therefore in different environments (local or CI), I still face different dates.

```
    MockDate.set('10/26/2017', 0);
    console.log(new Date().getTimezoneOffset());
    console.log(new Date().toString());
    console.log(new Date().toISOString());

    MockDate.set('10/26/2017', -120);
    console.log(new Date().getTimezoneOffset());
    console.log(new Date().toString());
    console.log(new Date().toISOString());
```

```
    0
    Thu Oct 26 2017 00:00:00 GMT+0200 (CEST)
    2017-10-25T22:00:00.000Z

    -120
    Thu Oct 26 2017 00:00:00 GMT+0200 (CEST)
    2017-10-25T22:00:00.000Z
```

**Comment by boblauer** [comment]
I regret adding the `timezoneOffset` parameter, because it is not fully implemented and leads to confusion such as this.

Would it work if you passed in a UTC string?  In other words, `MockDate.set('2017-10-25T22:00:00.000Z')`.  That's going to prevent the date from changing from one machine to the next.  The `toString()` method will still return a different value, because it takes into account the machine's current timezone, but `getTime` will return the same value regardless of the machine's timezone.

**Comment by luizdesign** [comment]
It works for me. I was disgusting already with an unit test that i need the time zone too. Thanks a lot.

**Comment by jguix** [comment]
How can this issue be closed?

**Comment by boblauer** [comment]
It's a known bug that involves too much code to fix. Setting the timezone to something else should be out of the scope of this library, and as such the `timezoneOffset` parameter should be removed from this library, rather than improved upon.

**Comment by gerisztein** [comment]
I managed to fix this issue adding `TZ=UTC` to my `.env` file.
